<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\User;
use App\Models\Participant;
use App\Enums\StatutParticipant;
use Illuminate\Support\Facades\DB;

class GroupeTest extends TestCase
{
    // Roll back DB changes after each test
    use DatabaseTransactions; 

    protected $user;   
    protected $participantId; 

    
    protected function setUp(): void
    {
        parent::setUp();

        // Create a participant and its linked user
        $this->user = User::factory()->create();
        
        $participant = Participant::factory()->create([
            'id_user' => $this->user->id,
        ]);
        
        
        $this->participantId = $participant->id;
    }

    public function test_participant_can_create_group_and_becomes_founder()
    {
        
        $payload = [
            'nom' => 'Les Fusées de Genève',
            'type' => 'Groupe', // or 'Entreprise'
            'code_entreprise' => null, // automatically generated by GroupeController
        ];
        
        // $this->user is created in setUp()
        $response = $this->actingAs($this->user)->postJson('/api/participant/groupes', $payload);
        
        // Validate HTTP response
        $response->assertStatus(201)
                 ->assertJsonStructure([
                     'id', 
                     'nom', 
                     'type', 
                     'participants'
                 ]);
        
        $this->assertDatabaseHas('Groupe', [
            'nom' => 'Les Fusées de Genève',
            'type' => 'Groupe',
        ]);
        
        $groupeId = $response->json('id');

        // Validate group-participant pivot row
        $this->assertDatabaseHas('GroupeParticipant', [
            'id_groupe' => $groupeId,
            'id_participant' => $this->participantId,
            'statut' => StatutParticipant::FONDATEUR->value,
        ]);
    }

    public function test_participant_can_invite_existing_participant()
    {
        
        // Create a group
        $groupeId = DB::table('Groupe')->insertGetId([
            'nom' => 'Les Aigles de Genève',
            'type' => 'Groupe',
        ]);

        // Attach current participant as founder
        DB::table('GroupeParticipant')->insert([
            'id_groupe'      => $groupeId,
            'id_participant' => $this->participantId,
            'statut'         => StatutParticipant::FONDATEUR->value,
        ]);

        // Create another participant to invite
        $ami = Participant::factory()->create();
        
        $payload = [
            'id_participant' => $ami->id,
        ];

        // Send POST request
        $response = $this->actingAs($this->user)
                         ->postJson("/api/participant/groupes/{$groupeId}/participants", $payload);

        $response->assertStatus(200)
                 ->assertJsonFragment([
                     'message' => 'Invitation envoyée (Participant ajouté en attente).',
                 ]);

        // Validate invitation row in pivot table
        $this->assertDatabaseHas('GroupeParticipant', [
            'id_groupe'      => $groupeId,
            'id_participant' => $ami->id,
            'statut'         => StatutParticipant::EN_ATTENTE->value,
        ]);
    }

    public function test_company_group_creation_generates_code_automatically()
    {
        $payload = [
            'nom'  => 'Rolex SA',
            'type' => 'Entreprise',
        ];

        // POST
        $response = $this->actingAs($this->user)
                         ->postJson('/api/participant/groupes', $payload);

        // Validate success response
        $response->assertStatus(201);

        
        $codeGenere = $response->json('code_entreprise');

        // Validate that a code is generated
        $this->assertNotNull($codeGenere);

        // Validate code format
        $this->assertMatchesRegularExpression('/^E-[A-Z0-9]{7}$/', $codeGenere);

        // Validate DB row contains generated code
        $this->assertDatabaseHas('Groupe', [
            'nom'             => 'Rolex SA',
            'type'            => 'Entreprise',
            'code_entreprise' => $codeGenere,
        ]);
    }
}